apiVersion: batch/v1
kind: Job
metadata:
  name: openclaw-cli
  namespace: openclaw
spec:
  template:
    metadata:
      name: openclaw-cli
    spec:
      restartPolicy: Never
      containers:
      - name: cli
        image: ghcr.io/openclaw/openclaw:latest
        env:
        - name: HOME
          value: /home/node
        - name: TERM
          value: xterm-256color
        - name: OPENCLAW_GATEWAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: openclaw-config
              key: OPENCLAW_GATEWAY_TOKEN
        volumeMounts:
        - name: openclaw-config
          mountPath: /home/node/.openclaw
        - name: openclaw-workspace
          mountPath: /home/node/.openclaw/workspace
        command: ["node", "dist/index.js"]