apiVersion: v1
kind: Service
metadata:
  name: openclaw-gateway
  namespace: openclaw
spec:
  selector:
    app: openclaw-gateway
  ports:
  - port: 18789
    targetPort: 18789
    name: gateway
  - port: 18790
    targetPort: 18790
    name: bridge
  type: LoadBalancer