---
# OpenClaw Kubernetes - Complete Manifest
# Apply with: kubectl apply -f openclaw-k8s.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: openclaw
  labels:
    app: openclaw

---
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-config
  namespace: openclaw
type: Opaque
stringData:
  # Generate with: openssl rand -hex 32
  OPENCLAW_GATEWAY_TOKEN: "replace-with-generated-token"

---
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-claude
  namespace: openclaw
type: Opaque
stringData:
  CLAUDE_AI_SESSION_KEY: ""
  CLAUDE_WEB_SESSION_KEY: ""
  CLAUDE_WEB_COOKIE: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-config-pvc
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-workspace-pvc
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw-gateway
  namespace: openclaw
  labels:
    app: openclaw-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openclaw-gateway
  template:
    metadata:
      labels:
        app: openclaw-gateway
    spec:
      # Node selector - label your nodes with: kubectl label nodes <node-name> openclaw-enabled=true
      nodeSelector:
        openclaw-enabled: "true"
      initContainers:
      - name: setup-directories
        image: busybox:latest
        command: ["sh", "-c", "mkdir -p /home/node/.openclaw /home/node/.openclaw/workspace"]
        volumeMounts:
        - name: openclaw-config
          mountPath: /home/node/.openclaw
        - name: openclaw-workspace
          mountPath: /home/node/.openclaw/workspace
      containers:
      - name: gateway
        image: ghcr.io/openclaw/openclaw:latest
        env:
        - name: HOME
          value: /home/node
        - name: TERM
          value: xterm-256color
        - name: OPENCLAW_GATEWAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: openclaw-config
              key: OPENCLAW_GATEWAY_TOKEN
        - name: CLAUDE_AI_SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: openclaw-claude
              key: CLAUDE_AI_SESSION_KEY
              optional: true
        - name: CLAUDE_WEB_SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: openclaw-claude
              key: CLAUDE_WEB_SESSION_KEY
              optional: true
        - name: CLAUDE_WEB_COOKIE
          valueFrom:
            secretKeyRef:
              name: openclaw-claude
              key: CLAUDE_WEB_COOKIE
              optional: true
        ports:
        - containerPort: 18789
          name: gateway
        - containerPort: 18790
          name: bridge
        volumeMounts:
        - name: openclaw-config
          mountPath: /home/node/.openclaw
        - name: openclaw-workspace
          mountPath: /home/node/.openclaw/workspace
        command: ["node", "dist/index.js", "gateway", "--bind", "lan", "--port", "18789"]
      volumes:
      - name: openclaw-config
        persistentVolumeClaim:
          claimName: openclaw-config-pvc
      - name: openclaw-workspace
        persistentVolumeClaim:
          claimName: openclaw-workspace-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: openclaw-gateway
  namespace: openclaw
spec:
  selector:
    app: openclaw-gateway
  ports:
  - port: 18789
    targetPort: 18789
    name: gateway
  - port: 18790
    targetPort: 18790
    name: bridge
  type: LoadBalancer

---
# Onboarding Job - run once, then delete or comment out
apiVersion: batch/v1
kind: Job
metadata:
  name: openclaw-onboarding
  namespace: openclaw
spec:
  template:
    metadata:
      name: openclaw-onboarding
    spec:
      nodeSelector:
        openclaw-enabled: "true"
      initContainers:
      - name: setup-directories
        image: busybox:latest
        command: ["sh", "-c", "mkdir -p /home/node/.openclaw /home/node/.openclaw/workspace"]
        volumeMounts:
        - name: openclaw-config
          mountPath: /home/node/.openclaw
        - name: openclaw-workspace
          mountPath: /home/node/.openclaw/workspace
      containers:
      - name: onboard
        image: ghcr.io/openclaw/openclaw:latest
        env:
        - name: HOME
          value: /home/node
        - name: TERM
          value: xterm-256color
        - name: OPENCLAW_GATEWAY_TOKEN
          valueFrom:
            secretKeyRef:
              name: openclaw-config
              key: OPENCLAW_GATEWAY_TOKEN
        stdin: true
        tty: true
        volumeMounts:
        - name: openclaw-config
          mountPath: /home/node/.openclaw
        - name: openclaw-workspace
          mountPath: /home/node/.openclaw/workspace
        command: ["node", "dist/index.js", "onboard", "--no-install-daemon"]
      volumes:
      - name: openclaw-config
        persistentVolumeClaim:
          claimName: openclaw-config-pvc
      - name: openclaw-workspace
        persistentVolumeClaim:
          claimName: openclaw-workspace-pvc
      restartPolicy: Never
  backoffLimit: 0